FROM yolean/kafka-transform-nodejs-runtime

ARG example=https://github.com/solsson/kafka-stateless-transform-nodejs-runtime/raw/49e7286b9bd479dec026a431494e79329f8874be

ADD ${example}/package.json /usr/src/app/package.json
ADD ${example}/index.js /usr/src/app/index.js
