version: "3.6"
services:
  zookeeper:
    image: solsson/kafka:1.0.0@sha256:17fdf1637426f45c93c65826670542e36b9f3394ede1cb61885c6a4befa8f72d
    entrypoint: ./bin/zookeeper-server-start.sh
    command:
    - ./config/zookeeper.properties
  kafka:
    image: solsson/kafka:1.0.0@sha256:17fdf1637426f45c93c65826670542e36b9f3394ede1cb61885c6a4befa8f72d
    links:
    - zookeeper
    entrypoint:
    - ./bin/kafka-server-start.sh
    - ./config/server.properties
    - --override
    -   listeners=PLAINTEXT://kafka:9092
    - --override
    -   advertised.listeners=PLAINTEXT://kafka:9092
    - --override
    -   zookeeper.connect=zookeeper:2181
    - --override
    -   log.retention.hours=-1
    - --override
    -   log.dirs=/var/lib/kafka/data/topics
    - --override
    -   auto.create.topics.enable=true
    - --override
    -   default.replication.factor=1
    - --override
    -   min.insync.replicas=1
  runtime:
    build: ../
    # TODO
    image: foo/bar
  kafkacat:
    image: solsson/kafkacat
    links:
    - kafka
    entrypoint:
      - bash
      - -cex
      - >
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      echo '{}' | kafkacat -b kafka:9092 -P -t example-topic