version: "3.6"
services:
  zookeeper:
    image: solsson/kafka:2.1.0@sha256:ac3f06d87d45c7be727863f31e79fbfdcb9c610b51ba9cf03c75a95d602f15e1
    entrypoint: ./bin/zookeeper-server-start.sh
    command:
    - ./config/zookeeper.properties
  kafka:
    image: solsson/kafka:2.1.0@sha256:ac3f06d87d45c7be727863f31e79fbfdcb9c610b51ba9cf03c75a95d602f15e1
    links:
    - zookeeper
    entrypoint:
    - ./bin/kafka-server-start.sh
    - ./config/server.properties
    - --override
    -   listeners=PLAINTEXT://kafka:9092
    - --override
    -   advertised.listeners=PLAINTEXT://kafka:9092
    - --override
    -   zookeeper.connect=zookeeper:2181
    - --override
    -   auto.create.topics.enable=true
    - --override
    -   background.threads=1
    - --override
    -   num.io.threads=1
    - --override
    -   num.network.threads=1
    - --override
    -   log.cleaner.enable=false
    - --override
    -   group.initial.rebalance.delay.ms=0
  runtime:
    build: ../
    image: yolean/kafka-transform-nodejs-runtime
    labels:
    - com.yolean.build-target
    entrypoint:
    - echo
    - "Runtime can't be started without a handler"
  sample-function-1:
    depends_on:
    - runtime
    build: ../sample-function-1
    environment:
      BOOTSTRAP: kafka:9092
      SOURCE_TOPIC: example-topic
      TARGET_TOPIC: example-out
  test-using-kafkacat:
    image: solsson/kafkacat@sha256:b91241b5741fccaef282eb8dbdfb6e5289bb8586274175b1836e57912ffecaef
    labels:
    - com.yolean.build-contract
    links:
    - kafka
    entrypoint:
    - bash
    - -cex
    - |
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      kafkacat -b kafka:9092 -C -t example-topic -e || echo "Waiting for kafka..."
      echo '{}' | kafkacat -b kafka:9092 -P -t example-topic
      sleep 10
      kafkacat -b kafka:9092 -C -t example-out -c 1
